import { Player } from './types';

export const SAMPLE_PLAYERS: Player[] = [
  // Quarterbacks - Top Tier
  {
    id: 'qb1',
    name: 'Caleb Williams',
    position: 'QB',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 22.5,
    passingYards: 3633,
    passingTDs: 30,
    completions: 310,
    attempts: 496,
    interceptions: 5,
    rushingYards: 382,
    rushingTDs: 6,
  },
  {
    id: 'qb2',
    name: 'Bo Nix',
    position: 'QB',
    team: 'Oregon',
    conference: 'Pac-12',
    projectedPoints: 21.2,
    passingYards: 4145,
    passingTDs: 45,
    completions: 317,
    attempts: 477,
    interceptions: 3,
    rushingYards: 510,
    rushingTDs: 14,
  },
  {
    id: 'qb3',
    name: 'J.J. McCarthy',
    position: 'QB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 20.8,
    passingYards: 2991,
    passingTDs: 22,
    completions: 214,
    attempts: 317,
    interceptions: 4,
    rushingYards: 202,
    rushingTDs: 3,
  },
  {
    id: 'qb4',
    name: 'Quinn Ewers',
    position: 'QB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 19.5,
    passingYards: 3479,
    passingTDs: 22,
    completions: 259,
    attempts: 392,
    interceptions: 6,
    rushingYards: 89,
    rushingTDs: 1,
  },
  {
    id: 'qb5',
    name: 'Carson Beck',
    position: 'QB',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 18.9,
    passingYards: 3941,
    passingTDs: 24,
    completions: 286,
    attempts: 417,
    interceptions: 6,
    rushingYards: 117,
    rushingTDs: 3,
  },
  {
    id: 'qb6',
    name: 'Drake Maye',
    position: 'QB',
    team: 'UNC',
    conference: 'ACC',
    projectedPoints: 18.2,
    passingYards: 4115,
    passingTDs: 38,
    completions: 315,
    attempts: 491,
    interceptions: 3,
    rushingYards: 698,
    rushingTDs: 9,
  },
  // Quarterbacks - Mid Tier
  {
    id: 'qb7',
    name: 'Shedeur Sanders',
    position: 'QB',
    team: 'Colorado',
    conference: 'Pac-12',
    projectedPoints: 17.8,
    passingYards: 3230,
    passingTDs: 27,
    completions: 298,
    attempts: 439,
    interceptions: 3,
    rushingYards: 86,
    rushingTDs: 4,
  },
  {
    id: 'qb8',
    name: 'Jayden Daniels',
    position: 'QB',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 17.5,
    passingYards: 3812,
    passingTDs: 40,
    completions: 327,
    attempts: 487,
    interceptions: 4,
    rushingYards: 1134,
    rushingTDs: 10,
  },
  {
    id: 'qb9',
    name: 'Michael Penix Jr.',
    position: 'QB',
    team: 'Washington',
    conference: 'Pac-12',
    projectedPoints: 17.2,
    passingYards: 4903,
    passingTDs: 36,
    completions: 346,
    attempts: 519,
    interceptions: 9,
    rushingYards: 38,
    rushingTDs: 1,
  },
  {
    id: 'qb10',
    name: 'Dillon Gabriel',
    position: 'QB',
    team: 'Oklahoma',
    conference: 'Big 12',
    projectedPoints: 16.9,
    passingYards: 3660,
    passingTDs: 30,
    completions: 304,
    attempts: 425,
    interceptions: 4,
    rushingYards: 412,
    rushingTDs: 12,
  },
  {
    id: 'qb11',
    name: 'Jordan Travis',
    position: 'QB',
    team: 'Florida State',
    conference: 'ACC',
    projectedPoints: 16.5,
    passingYards: 2756,
    passingTDs: 20,
    completions: 209,
    attempts: 329,
    interceptions: 2,
    rushingYards: 526,
    rushingTDs: 14,
  },
  {
    id: 'qb12',
    name: 'Cam Rising',
    position: 'QB',
    team: 'Utah',
    conference: 'Pac-12',
    projectedPoints: 16.2,
    passingYards: 2493,
    passingTDs: 20,
    completions: 186,
    attempts: 280,
    interceptions: 5,
    rushingYards: 442,
    rushingTDs: 7,
  },
  {
    id: 'qb13',
    name: 'Tyler Van Dyke',
    position: 'QB',
    team: 'Miami',
    conference: 'ACC',
    projectedPoints: 15.8,
    passingYards: 2790,
    passingTDs: 19,
    completions: 213,
    attempts: 356,
    interceptions: 9,
    rushingYards: 89,
    rushingTDs: 1,
  },
  {
    id: 'qb14',
    name: 'DJ Uiagalelei',
    position: 'QB',
    team: 'Oregon State',
    conference: 'Pac-12',
    projectedPoints: 15.5,
    passingYards: 2638,
    passingTDs: 21,
    completions: 223,
    attempts: 378,
    interceptions: 7,
    rushingYards: 268,
    rushingTDs: 5,
  },
  {
    id: 'qb15',
    name: 'KJ Jefferson',
    position: 'QB',
    team: 'UCF',
    conference: 'Big 12',
    projectedPoints: 15.2,
    passingYards: 2107,
    passingTDs: 18,
    completions: 157,
    attempts: 268,
    interceptions: 3,
    rushingYards: 321,
    rushingTDs: 6,
  },

  // Running Backs - Top Tier
  {
    id: 'rb1',
    name: 'Blake Corum',
    position: 'RB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 16.8,
    rushingYards: 1245,
    rushingTDs: 27,
    receivingYards: 187,
    receptions: 16,
    receivingTDs: 1,
  },
  {
    id: 'rb2',
    name: 'Bijan Robinson',
    position: 'RB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 16.2,
    rushingYards: 1580,
    rushingTDs: 18,
    receivingYards: 314,
    receptions: 25,
    receivingTDs: 2,
  },
  {
    id: 'rb3',
    name: 'Travis Dye',
    position: 'RB',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 15.5,
    rushingYards: 1213,
    rushingTDs: 16,
    receivingYards: 297,
    receptions: 29,
    receivingTDs: 3,
  },
  {
    id: 'rb4',
    name: 'Devon Achane',
    position: 'RB',
    team: 'Texas A&M',
    conference: 'SEC',
    projectedPoints: 15.1,
    rushingYards: 1009,
    rushingTDs: 8,
    receivingYards: 261,
    receptions: 17,
    receivingTDs: 3,
    returnYards: 445,
  },
  {
    id: 'rb5',
    name: 'Zach Charbonnet',
    position: 'RB',
    team: 'UCLA',
    conference: 'Pac-12',
    projectedPoints: 14.8,
    rushingYards: 1359,
    rushingTDs: 14,
    receivingYards: 213,
    receptions: 20,
    receivingTDs: 1,
  },
  {
    id: 'rb6',
    name: 'Sean Tucker',
    position: 'RB',
    team: 'Syracuse',
    conference: 'ACC',
    projectedPoints: 14.3,
    rushingYards: 1496,
    rushingTDs: 12,
    receivingYards: 304,
    receptions: 24,
    receivingTDs: 2,
  },
  {
    id: 'rb7',
    name: 'Tank Bigsby',
    position: 'RB',
    team: 'Auburn',
    conference: 'SEC',
    projectedPoints: 13.9,
    rushingYards: 1099,
    rushingTDs: 10,
    receivingYards: 145,
    receptions: 12,
    receivingTDs: 1,
  },
  {
    id: 'rb8',
    name: 'Israel Abanikanda',
    position: 'RB',
    team: 'Pittsburgh',
    conference: 'ACC',
    projectedPoints: 13.5,
    rushingYards: 1431,
    rushingTDs: 20,
    receivingYards: 277,
    receptions: 20,
    receivingTDs: 1,
  },
  // Running Backs - Mid Tier
  {
    id: 'rb9',
    name: 'Donovan Edwards',
    position: 'RB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 13.2,
    rushingYards: 1187,
    rushingTDs: 7,
    receivingYards: 216,
    receptions: 15,
    receivingTDs: 1,
  },
  {
    id: 'rb10',
    name: 'Jordan Mason',
    position: 'RB',
    team: 'Georgia Tech',
    conference: 'ACC',
    projectedPoints: 12.8,
    rushingYards: 899,
    rushingTDs: 9,
    receivingYards: 132,
    receptions: 8,
    receivingTDs: 0,
  },
  {
    id: 'rb11',
    name: 'Roschon Johnson',
    position: 'RB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 12.5,
    rushingYards: 815,
    rushingTDs: 11,
    receivingYards: 223,
    receptions: 19,
    receivingTDs: 2,
  },
  {
    id: 'rb12',
    name: 'TreVeyon Henderson',
    position: 'RB',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 12.2,
    rushingYards: 571,
    rushingTDs: 6,
    receivingYards: 101,
    receptions: 10,
    receivingTDs: 1,
  },
  {
    id: 'rb13',
    name: 'Dameon Pierce',
    position: 'RB',
    team: 'Florida',
    conference: 'SEC',
    projectedPoints: 11.9,
    rushingYards: 574,
    rushingTDs: 13,
    receivingYards: 216,
    receptions: 19,
    receivingTDs: 3,
  },
  {
    id: 'rb14',
    name: 'Chase Brown',
    position: 'RB',
    team: 'Illinois',
    conference: 'Big Ten',
    projectedPoints: 11.6,
    rushingYards: 1643,
    rushingTDs: 10,
    receivingYards: 168,
    receptions: 16,
    receivingTDs: 0,
  },
  {
    id: 'rb15',
    name: 'Kenneth Walker III',
    position: 'RB',
    team: 'Michigan State',
    conference: 'Big Ten',
    projectedPoints: 11.3,
    rushingYards: 1636,
    rushingTDs: 18,
    receivingYards: 89,
    receptions: 13,
    receivingTDs: 1,
  },
  {
    id: 'rb16',
    name: 'Tyler Allgeier',
    position: 'RB',
    team: 'BYU',
    conference: 'Independent',
    projectedPoints: 11.0,
    rushingYards: 1601,
    rushingTDs: 23,
    receivingYards: 199,
    receptions: 28,
    receivingTDs: 1,
  },
  {
    id: 'rb17',
    name: 'Tyjae Spears',
    position: 'RB',
    team: 'Tulane',
    conference: 'AAC',
    projectedPoints: 10.7,
    rushingYards: 1524,
    rushingTDs: 19,
    receivingYards: 215,
    receptions: 14,
    receivingTDs: 0,
  },
  {
    id: 'rb18',
    name: 'Deuce Vaughn',
    position: 'RB',
    team: 'Kansas State',
    conference: 'Big 12',
    projectedPoints: 10.4,
    rushingYards: 1404,
    rushingTDs: 22,
    receivingYards: 468,
    receptions: 47,
    receivingTDs: 1,
  },

  // Wide Receivers - Top Tier
  {
    id: 'wr1',
    name: 'Marvin Harrison Jr.',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 18.3,
    receivingYards: 1211,
    receptions: 67,
    receivingTDs: 14,
  },
  {
    id: 'wr2',
    name: 'Rome Odunze',
    position: 'WR',
    team: 'Washington',
    conference: 'Pac-12',
    projectedPoints: 17.8,
    receivingYards: 1640,
    receptions: 92,
    receivingTDs: 13,
  },
  {
    id: 'wr3',
    name: 'Malik Nabers',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 17.2,
    receivingYards: 1569,
    receptions: 89,
    receivingTDs: 14,
    returnYards: 234,
  },
  {
    id: 'wr4',
    name: 'Ladd McConkey',
    position: 'WR',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 16.5,
    receivingYards: 1187,
    receptions: 58,
    receivingTDs: 8,
    returnYards: 312,
  },
  {
    id: 'wr5',
    name: 'Keon Coleman',
    position: 'WR',
    team: 'Florida State',
    conference: 'ACC',
    projectedPoints: 16.1,
    receivingYards: 658,
    receptions: 50,
    receivingTDs: 11,
  },
  {
    id: 'wr6',
    name: 'Brian Thomas Jr.',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 15.8,
    receivingYards: 1177,
    receptions: 68,
    receivingTDs: 17,
  },
  {
    id: 'wr7',
    name: 'Xavier Worthy',
    position: 'WR',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 15.4,
    receivingYards: 1014,
    receptions: 75,
    receivingTDs: 5,
    returnYards: 156,
  },
  {
    id: 'wr8',
    name: 'Adonai Mitchell',
    position: 'WR',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 15.0,
    receivingYards: 845,
    receptions: 55,
    receivingTDs: 11,
  },
  {
    id: 'wr9',
    name: 'Troy Franklin',
    position: 'WR',
    team: 'Oregon',
    conference: 'Pac-12',
    projectedPoints: 14.7,
    receivingYards: 1383,
    receptions: 81,
    receivingTDs: 14,
  },
  {
    id: 'wr10',
    name: 'Emeka Egbuka',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 14.3,
    receivingYards: 1151,
    receptions: 69,
    receivingTDs: 10,
  },
  // Wide Receivers - Mid Tier
  {
    id: 'wr11',
    name: 'Jordan Addison',
    position: 'WR',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 14.0,
    receivingYards: 1593,
    receptions: 100,
    receivingTDs: 8,
  },
  {
    id: 'wr12',
    name: 'Jaylen Reed',
    position: 'WR',
    team: 'Michigan State',
    conference: 'Big Ten',
    projectedPoints: 13.7,
    receivingYards: 1026,
    receptions: 64,
    receivingTDs: 10,
  },
  {
    id: 'wr13',
    name: 'Jaxon Smith-Njigba',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 13.4,
    receivingYards: 347,
    receptions: 28,
    receivingTDs: 5,
  },
  {
    id: 'wr14',
    name: 'Quentin Johnston',
    position: 'WR',
    team: 'TCU',
    conference: 'Big 12',
    projectedPoints: 13.1,
    receivingYards: 1055,
    receptions: 60,
    receivingTDs: 6,
  },
  {
    id: 'wr15',
    name: 'Cedric Tillman',
    position: 'WR',
    team: 'Tennessee',
    conference: 'SEC',
    projectedPoints: 12.8,
    receivingYards: 1081,
    receptions: 64,
    receivingTDs: 12,
  },
  {
    id: 'wr16',
    name: 'Tre Tucker',
    position: 'WR',
    team: 'Cincinnati',
    conference: 'AAC',
    projectedPoints: 12.5,
    receivingYards: 761,
    receptions: 54,
    receivingTDs: 6,
    returnYards: 578,
  },
  {
    id: 'wr17',
    name: 'Dontay Demus Jr.',
    position: 'WR',
    team: 'Maryland',
    conference: 'Big Ten',
    projectedPoints: 12.2,
    receivingYards: 526,
    receptions: 27,
    receivingTDs: 3,
  },
  {
    id: 'wr18',
    name: 'Terrace Marshall Jr.',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 11.9,
    receivingYards: 671,
    receptions: 48,
    receivingTDs: 10,
  },
  {
    id: 'wr19',
    name: 'Chris Olave',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 11.6,
    receivingYards: 936,
    receptions: 65,
    receivingTDs: 13,
  },
  {
    id: 'wr20',
    name: 'DeVonta Smith',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 11.3,
    receivingYards: 1856,
    receptions: 117,
    receivingTDs: 23,
    returnYards: 89,
  },
  {
    id: 'wr21',
    name: 'Jerry Jeudy',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 11.0,
    receivingYards: 1163,
    receptions: 77,
    receivingTDs: 10,
  },
  {
    id: 'wr22',
    name: 'CeeDee Lamb',
    position: 'WR',
    team: 'Oklahoma',
    conference: 'Big 12',
    projectedPoints: 10.7,
    receivingYards: 1327,
    receptions: 62,
    receivingTDs: 14,
    returnYards: 235,
  },
  {
    id: 'wr23',
    name: 'Henry Ruggs III',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 10.4,
    receivingYards: 746,
    receptions: 40,
    receivingTDs: 7,
    returnYards: 123,
  },
  {
    id: 'wr24',
    name: 'Jaylen Waddle',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 10.1,
    receivingYards: 557,
    receptions: 45,
    receivingTDs: 4,
    returnYards: 194,
  },
];

// Conference lists for filtering
export const CONFERENCES = [
  'All Conferences',
  'SEC',
  'Big Ten',
  'Big 12',
  'ACC',
  'Pac-12',
  'AAC',
  'Independent'
];

// Team lists for filtering
export const TEAMS = [
  'All Teams',
  // SEC
  'Alabama', 'Auburn', 'Florida', 'Georgia', 'LSU', 'Tennessee', 'Texas A&M',
  // Big Ten
  'Michigan', 'Ohio State', 'Michigan State', 'Illinois', 'Maryland',
  // Big 12
  'Texas', 'Oklahoma', 'TCU', 'Kansas State', 'UCF',
  // ACC
  'Florida State', 'Miami', 'UNC', 'Pittsburgh', 'Syracuse', 'Georgia Tech',
  // Pac-12
  'USC', 'Oregon', 'Washington', 'UCLA', 'Colorado', 'Utah', 'Oregon State',
  // AAC
  'Cincinnati', 'Tulane',
  // Independent
  'BYU'
];