import { Player } from './types';
import { fetchCurrentPlayers, getCurrentConferences, getCurrentTeams } from './api';

// Cache for API data
let playersCache: Player[] = [];
let conferencesCache: string[] = [];
let teamsCache: string[] = [];
let cacheTimestamp = 0;
const CACHE_DURATION = 30 * 60 * 1000; // 30 minutes

// Check if cache is valid
const isCacheValid = () => {
  return Date.now() - cacheTimestamp < CACHE_DURATION;
};

// Main function to get players (with caching)
export const getPlayers = async (): Promise<Player[]> => {
  if (playersCache.length > 0 && isCacheValid()) {
    return playersCache;
  }

  try {
    playersCache = await fetchCurrentPlayers();
    cacheTimestamp = Date.now();
    return playersCache;
  } catch (error) {
    console.error('Failed to fetch current players, using sample data:', error);
    return SAMPLE_PLAYERS;
  }
};

// Get conferences (with caching)
export const getConferences = async (): Promise<string[]> => {
  if (conferencesCache.length > 0 && isCacheValid()) {
    return conferencesCache;
  }

  try {
    conferencesCache = await getCurrentConferences();
    return conferencesCache;
  } catch (error) {
    console.error('Failed to fetch conferences, using default:', error);
    return CONFERENCES;
  }
};

// Get teams (with caching)
export const getTeams = async (): Promise<string[]> => {
  if (teamsCache.length > 0 && isCacheValid()) {
    return teamsCache;
  }

  try {
    teamsCache = await getCurrentTeams();
    return teamsCache;
  } catch (error) {
    console.error('Failed to fetch teams, using default:', error);
    return TEAMS;
  }
};

// Clear cache (useful for refreshing data)
export const clearCache = () => {
  playersCache = [];
  conferencesCache = [];
  teamsCache = [];
  cacheTimestamp = 0;
};

// Fallback sample data for when API is not available
export const SAMPLE_PLAYERS: Player[] = [
  // Quarterbacks - Top Tier
  {
    id: 'qb1',
    name: 'Caleb Williams',
    position: 'QB',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 22.5,
    passingYards: 3633,
    passingTDs: 30,
    completions: 310,
    attempts: 496,
    interceptions: 5,
    rushingYards: 382,
    rushingTDs: 6,
  },
  {
    id: 'qb2',
    name: 'Bo Nix',
    position: 'QB',
    team: 'Oregon',
    conference: 'Pac-12',
    projectedPoints: 21.2,
    passingYards: 4145,
    passingTDs: 45,
    completions: 317,
    attempts: 477,
    interceptions: 3,
    rushingYards: 510,
    rushingTDs: 14,
  },
  {
    id: 'qb3',
    name: 'J.J. McCarthy',
    position: 'QB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 20.8,
    passingYards: 2991,
    passingTDs: 22,
    completions: 214,
    attempts: 317,
    interceptions: 4,
    rushingYards: 202,
    rushingTDs: 3,
  },
  {
    id: 'qb4',
    name: 'Quinn Ewers',
    position: 'QB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 19.5,
    passingYards: 3479,
    passingTDs: 22,
    completions: 259,
    attempts: 392,
    interceptions: 6,
    rushingYards: 89,
    rushingTDs: 1,
  },
  {
    id: 'qb5',
    name: 'Carson Beck',
    position: 'QB',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 18.9,
    passingYards: 3941,
    passingTDs: 24,
    completions: 286,
    attempts: 417,
    interceptions: 6,
    rushingYards: 117,
    rushingTDs: 3,
  },
  {
    id: 'qb6',
    name: 'Drake Maye',
    position: 'QB',
    team: 'UNC',
    conference: 'ACC',
    projectedPoints: 18.2,
    passingYards: 4115,
    passingTDs: 38,
    completions: 315,
    attempts: 491,
    interceptions: 3,
    rushingYards: 698,
    rushingTDs: 9,
  },
  // Quarterbacks - Mid Tier
  {
    id: 'qb7',
    name: 'Shedeur Sanders',
    position: 'QB',
    team: 'Colorado',
    conference: 'Pac-12',
    projectedPoints: 17.8,
    passingYards: 3230,
    passingTDs: 27,
    completions: 298,
    attempts: 439,
    interceptions: 3,
    rushingYards: 86,
    rushingTDs: 4,
  },
  {
    id: 'qb8',
    name: 'Jayden Daniels',
    position: 'QB',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 17.5,
    passingYards: 3812,
    passingTDs: 40,
    completions: 327,
    attempts: 487,
    interceptions: 4,
    rushingYards: 1134,
    rushingTDs: 10,
  },
  {
    id: 'qb9',
    name: 'Michael Penix Jr.',
    position: 'QB',
    team: 'Washington',
    conference: 'Pac-12',
    projectedPoints: 17.2,
    passingYards: 4903,
    passingTDs: 36,
    completions: 346,
    attempts: 519,
    interceptions: 9,
    rushingYards: 38,
    rushingTDs: 1,
  },
  {
    id: 'qb10',
    name: 'Dillon Gabriel',
    position: 'QB',
    team: 'Oklahoma',
    conference: 'Big 12',
    projectedPoints: 16.9,
    passingYards: 3660,
    passingTDs: 30,
    completions: 304,
    attempts: 425,
    interceptions: 4,
    rushingYards: 412,
    rushingTDs: 12,
  },
  {
    id: 'qb11',
    name: 'Jordan Travis',
    position: 'QB',
    team: 'Florida State',
    conference: 'ACC',
    projectedPoints: 16.5,
    passingYards: 2756,
    passingTDs: 20,
    completions: 209,
    attempts: 329,
    interceptions: 2,
    rushingYards: 526,
    rushingTDs: 14,
  },
  {
    id: 'qb12',
    name: 'Cam Rising',
    position: 'QB',
    team: 'Utah',
    conference: 'Pac-12',
    projectedPoints: 16.2,
    passingYards: 2493,
    passingTDs: 20,
    completions: 186,
    attempts: 280,
    interceptions: 5,
    rushingYards: 442,
    rushingTDs: 7,
  },
  {
    id: 'qb13',
    name: 'Tyler Van Dyke',
    position: 'QB',
    team: 'Miami',
    conference: 'ACC',
    projectedPoints: 15.8,
    passingYards: 2790,
    passingTDs: 19,
    completions: 213,
    attempts: 356,
    interceptions: 9,
    rushingYards: 89,
    rushingTDs: 1,
  },
  {
    id: 'qb14',
    name: 'DJ Uiagalelei',
    position: 'QB',
    team: 'Oregon State',
    conference: 'Pac-12',
    projectedPoints: 15.5,
    passingYards: 2638,
    passingTDs: 21,
    completions: 223,
    attempts: 378,
    interceptions: 7,
    rushingYards: 268,
    rushingTDs: 5,
  },
  {
    id: 'qb15',
    name: 'KJ Jefferson',
    position: 'QB',
    team: 'UCF',
    conference: 'Big 12',
    projectedPoints: 15.2,
    passingYards: 2107,
    passingTDs: 18,
    completions: 157,
    attempts: 268,
    interceptions: 3,
    rushingYards: 321,
    rushingTDs: 6,
  },
  // More Quarterbacks
  {
    id: 'qb16',
    name: 'Spencer Rattler',
    position: 'QB',
    team: 'South Carolina',
    conference: 'SEC',
    projectedPoints: 14.9,
    passingYards: 3026,
    passingTDs: 18,
    completions: 238,
    attempts: 399,
    interceptions: 12,
    rushingYards: 104,
    rushingTDs: 3,
  },
  {
    id: 'qb17',
    name: 'Tanner McKee',
    position: 'QB',
    team: 'Stanford',
    conference: 'Pac-12',
    projectedPoints: 14.6,
    passingYards: 3061,
    passingTDs: 15,
    completions: 234,
    attempts: 385,
    interceptions: 7,
    rushingYards: 56,
    rushingTDs: 2,
  },
  {
    id: 'qb18',
    name: 'Grayson McCall',
    position: 'QB',
    team: 'Coastal Carolina',
    conference: 'Sun Belt',
    projectedPoints: 14.3,
    passingYards: 2664,
    passingTDs: 27,
    completions: 203,
    attempts: 295,
    interceptions: 3,
    rushingYards: 220,
    rushingTDs: 5,
  },
  {
    id: 'qb19',
    name: 'Malik Cunningham',
    position: 'QB',
    team: 'Louisville',
    conference: 'ACC',
    projectedPoints: 14.0,
    passingYards: 2941,
    passingTDs: 20,
    completions: 207,
    attempts: 334,
    interceptions: 7,
    rushingYards: 1031,
    rushingTDs: 20,
  },
  {
    id: 'qb20',
    name: 'Graham Mertz',
    position: 'QB',
    team: 'Florida',
    conference: 'SEC',
    projectedPoints: 13.7,
    passingYards: 2843,
    passingTDs: 17,
    completions: 213,
    attempts: 344,
    interceptions: 11,
    rushingYards: 89,
    rushingTDs: 1,
  },
  {
    id: 'qb21',
    name: 'Tommy DeVito',
    position: 'QB',
    team: 'Syracuse',
    conference: 'ACC',
    projectedPoints: 13.4,
    passingYards: 2381,
    passingTDs: 19,
    completions: 188,
    attempts: 317,
    interceptions: 5,
    rushingYards: 145,
    rushingTDs: 3,
  },
  {
    id: 'qb22',
    name: 'Hendon Hooker',
    position: 'QB',
    team: 'Tennessee',
    conference: 'SEC',
    projectedPoints: 13.1,
    passingYards: 3135,
    passingTDs: 27,
    completions: 236,
    attempts: 355,
    interceptions: 2,
    rushingYards: 616,
    rushingTDs: 5,
  },
  {
    id: 'qb23',
    name: 'Anthony Richardson',
    position: 'QB',
    team: 'Florida',
    conference: 'SEC',
    projectedPoints: 12.8,
    passingYards: 2549,
    passingTDs: 17,
    completions: 160,
    attempts: 327,
    interceptions: 9,
    rushingYards: 654,
    rushingTDs: 9,
  },
  {
    id: 'qb24',
    name: 'Will Levis',
    position: 'QB',
    team: 'Kentucky',
    conference: 'SEC',
    projectedPoints: 12.5,
    passingYards: 2826,
    passingTDs: 24,
    completions: 230,
    attempts: 383,
    interceptions: 13,
    rushingYards: 376,
    rushingTDs: 9,
  },
  {
    id: 'qb25',
    name: 'Bryce Young',
    position: 'QB',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 12.2,
    passingYards: 3328,
    passingTDs: 35,
    completions: 366,
    attempts: 547,
    interceptions: 7,
    rushingYards: 8,
    rushingTDs: 1,
  },
  {
    id: 'qb26',
    name: 'Sam Hartman',
    position: 'QB',
    team: 'Notre Dame',
    conference: 'Independent',
    projectedPoints: 11.9,
    passingYards: 4228,
    passingTDs: 38,
    completions: 312,
    attempts: 471,
    interceptions: 12,
    rushingYards: 126,
    rushingTDs: 5,
  },
  {
    id: 'qb27',
    name: 'C.J. Stroud',
    position: 'QB',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 11.6,
    passingYards: 3862,
    passingTDs: 44,
    completions: 317,
    attempts: 441,
    interceptions: 6,
    rushingYards: 108,
    rushingTDs: 1,
  },
  {
    id: 'qb28',
    name: 'Jake Haener',
    position: 'QB',
    team: 'Fresno State',
    conference: 'Mountain West',
    projectedPoints: 11.3,
    passingYards: 4096,
    passingTDs: 33,
    completions: 365,
    attempts: 551,
    interceptions: 14,
    rushingYards: 56,
    rushingTDs: 2,
  },
  {
    id: 'qb29',
    name: 'Dorian Thompson-Robinson',
    position: 'QB',
    team: 'UCLA',
    conference: 'Pac-12',
    projectedPoints: 11.0,
    passingYards: 2409,
    passingTDs: 21,
    completions: 173,
    attempts: 295,
    interceptions: 6,
    rushingYards: 609,
    rushingTDs: 4,
  },
  {
    id: 'qb30',
    name: 'Phil Jurkovec',
    position: 'QB',
    team: 'Boston College',
    conference: 'ACC',
    projectedPoints: 10.7,
    passingYards: 2558,
    passingTDs: 18,
    completions: 183,
    attempts: 324,
    interceptions: 5,
    rushingYards: 123,
    rushingTDs: 3,
  },

  // Running Backs - Top Tier
  {
    id: 'rb1',
    name: 'Blake Corum',
    position: 'RB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 16.8,
    rushingYards: 1245,
    rushingTDs: 27,
    receivingYards: 187,
    receptions: 16,
    receivingTDs: 1,
  },
  {
    id: 'rb2',
    name: 'Bijan Robinson',
    position: 'RB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 16.2,
    rushingYards: 1580,
    rushingTDs: 18,
    receivingYards: 314,
    receptions: 25,
    receivingTDs: 2,
  },
  {
    id: 'rb3',
    name: 'Travis Dye',
    position: 'RB',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 15.5,
    rushingYards: 1213,
    rushingTDs: 16,
    receivingYards: 297,
    receptions: 29,
    receivingTDs: 3,
  },
  {
    id: 'rb4',
    name: 'Devon Achane',
    position: 'RB',
    team: 'Texas A&M',
    conference: 'SEC',
    projectedPoints: 15.1,
    rushingYards: 1009,
    rushingTDs: 8,
    receivingYards: 261,
    receptions: 17,
    receivingTDs: 3,
    returnYards: 445,
  },
  {
    id: 'rb5',
    name: 'Zach Charbonnet',
    position: 'RB',
    team: 'UCLA',
    conference: 'Pac-12',
    projectedPoints: 14.8,
    rushingYards: 1359,
    rushingTDs: 14,
    receivingYards: 213,
    receptions: 20,
    receivingTDs: 1,
  },
  {
    id: 'rb6',
    name: 'Sean Tucker',
    position: 'RB',
    team: 'Syracuse',
    conference: 'ACC',
    projectedPoints: 14.3,
    rushingYards: 1496,
    rushingTDs: 12,
    receivingYards: 304,
    receptions: 24,
    receivingTDs: 2,
  },
  {
    id: 'rb7',
    name: 'Tank Bigsby',
    position: 'RB',
    team: 'Auburn',
    conference: 'SEC',
    projectedPoints: 13.9,
    rushingYards: 1099,
    rushingTDs: 10,
    receivingYards: 145,
    receptions: 12,
    receivingTDs: 1,
  },
  {
    id: 'rb8',
    name: 'Israel Abanikanda',
    position: 'RB',
    team: 'Pittsburgh',
    conference: 'ACC',
    projectedPoints: 13.5,
    rushingYards: 1431,
    rushingTDs: 20,
    receivingYards: 277,
    receptions: 20,
    receivingTDs: 1,
  },
  // Running Backs - Mid Tier
  {
    id: 'rb9',
    name: 'Donovan Edwards',
    position: 'RB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 13.2,
    rushingYards: 1187,
    rushingTDs: 7,
    receivingYards: 216,
    receptions: 15,
    receivingTDs: 1,
  },
  {
    id: 'rb10',
    name: 'Jordan Mason',
    position: 'RB',
    team: 'Georgia Tech',
    conference: 'ACC',
    projectedPoints: 12.8,
    rushingYards: 899,
    rushingTDs: 9,
    receivingYards: 132,
    receptions: 8,
    receivingTDs: 0,
  },
  {
    id: 'rb11',
    name: 'Roschon Johnson',
    position: 'RB',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 12.5,
    rushingYards: 815,
    rushingTDs: 11,
    receivingYards: 223,
    receptions: 19,
    receivingTDs: 2,
  },
  {
    id: 'rb12',
    name: 'TreVeyon Henderson',
    position: 'RB',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 12.2,
    rushingYards: 571,
    rushingTDs: 6,
    receivingYards: 101,
    receptions: 10,
    receivingTDs: 1,
  },
  {
    id: 'rb13',
    name: 'Dameon Pierce',
    position: 'RB',
    team: 'Florida',
    conference: 'SEC',
    projectedPoints: 11.9,
    rushingYards: 574,
    rushingTDs: 13,
    receivingYards: 216,
    receptions: 19,
    receivingTDs: 3,
  },
  {
    id: 'rb14',
    name: 'Chase Brown',
    position: 'RB',
    team: 'Illinois',
    conference: 'Big Ten',
    projectedPoints: 11.6,
    rushingYards: 1643,
    rushingTDs: 10,
    receivingYards: 168,
    receptions: 16,
    receivingTDs: 0,
  },
  {
    id: 'rb15',
    name: 'Kenneth Walker III',
    position: 'RB',
    team: 'Michigan State',
    conference: 'Big Ten',
    projectedPoints: 11.3,
    rushingYards: 1636,
    rushingTDs: 18,
    receivingYards: 89,
    receptions: 13,
    receivingTDs: 1,
  },
  {
    id: 'rb16',
    name: 'Tyler Allgeier',
    position: 'RB',
    team: 'BYU',
    conference: 'Independent',
    projectedPoints: 11.0,
    rushingYards: 1601,
    rushingTDs: 23,
    receivingYards: 199,
    receptions: 28,
    receivingTDs: 1,
  },
  {
    id: 'rb17',
    name: 'Tyjae Spears',
    position: 'RB',
    team: 'Tulane',
    conference: 'AAC',
    projectedPoints: 10.7,
    rushingYards: 1524,
    rushingTDs: 19,
    receivingYards: 215,
    receptions: 14,
    receivingTDs: 0,
  },
  {
    id: 'rb18',
    name: 'Deuce Vaughn',
    position: 'RB',
    team: 'Kansas State',
    conference: 'Big 12',
    projectedPoints: 10.4,
    rushingYards: 1404,
    rushingTDs: 22,
    receivingYards: 468,
    receptions: 47,
    receivingTDs: 1,
  },
  // More Running Backs
  {
    id: 'rb19',
    name: 'Jaylen Warren',
    position: 'RB',
    team: 'Oklahoma State',
    conference: 'Big 12',
    projectedPoints: 10.1,
    rushingYards: 1134,
    rushingTDs: 11,
    receivingYards: 285,
    receptions: 36,
    receivingTDs: 2,
  },
  {
    id: 'rb20',
    name: 'Rachaad White',
    position: 'RB',
    team: 'Arizona State',
    conference: 'Pac-12',
    projectedPoints: 9.8,
    rushingYards: 1145,
    rushingTDs: 15,
    receivingYards: 456,
    receptions: 43,
    receivingTDs: 1,
  },
  {
    id: 'rb21',
    name: 'Jerome Ford',
    position: 'RB',
    team: 'Cincinnati',
    conference: 'AAC',
    projectedPoints: 9.5,
    rushingYards: 1319,
    rushingTDs: 19,
    receivingYards: 220,
    receptions: 21,
    receivingTDs: 1,
  },
  {
    id: 'rb22',
    name: 'Isaiah Spiller',
    position: 'RB',
    team: 'Texas A&M',
    conference: 'SEC',
    projectedPoints: 9.2,
    rushingYards: 1011,
    rushingTDs: 6,
    receivingYards: 189,
    receptions: 23,
    receivingTDs: 2,
  },
  {
    id: 'rb23',
    name: 'Brian Robinson Jr.',
    position: 'RB',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 8.9,
    rushingYards: 1343,
    rushingTDs: 14,
    receivingYards: 296,
    receptions: 35,
    receivingTDs: 2,
  },
  {
    id: 'rb24',
    name: 'Zamir White',
    position: 'RB',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 8.6,
    rushingYards: 856,
    rushingTDs: 11,
    receivingYards: 97,
    receptions: 11,
    receivingTDs: 0,
  },
  {
    id: 'rb25',
    name: 'Breece Hall',
    position: 'RB',
    team: 'Iowa State',
    conference: 'Big 12',
    projectedPoints: 8.3,
    rushingYards: 1472,
    rushingTDs: 21,
    receivingYards: 302,
    receptions: 26,
    receivingTDs: 3,
  },
  {
    id: 'rb26',
    name: 'Hassan Haskins',
    position: 'RB',
    team: 'Michigan',
    conference: 'Big Ten',
    projectedPoints: 8.0,
    rushingYards: 1327,
    rushingTDs: 20,
    receivingYards: 65,
    receptions: 7,
    receivingTDs: 0,
  },
  {
    id: 'rb27',
    name: 'James Cook',
    position: 'RB',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 7.7,
    rushingYards: 728,
    rushingTDs: 7,
    receivingYards: 284,
    receptions: 30,
    receivingTDs: 4,
  },
  {
    id: 'rb28',
    name: 'Leddie Brown',
    position: 'RB',
    team: 'West Virginia',
    conference: 'Big 12',
    projectedPoints: 7.4,
    rushingYards: 1010,
    rushingTDs: 8,
    receivingYards: 102,
    receptions: 14,
    receivingTDs: 0,
  },
  {
    id: 'rb29',
    name: 'Max Borghi',
    position: 'RB',
    team: 'Washington State',
    conference: 'Pac-12',
    projectedPoints: 7.1,
    rushingYards: 817,
    rushingTDs: 11,
    receivingYards: 408,
    receptions: 40,
    receivingTDs: 3,
  },
  {
    id: 'rb30',
    name: 'Kyren Williams',
    position: 'RB',
    team: 'Notre Dame',
    conference: 'Independent',
    projectedPoints: 6.8,
    rushingYards: 1002,
    rushingTDs: 14,
    receivingYards: 359,
    receptions: 42,
    receivingTDs: 3,
  },
  {
    id: 'rb31',
    name: 'Abram Smith',
    position: 'RB',
    team: 'Baylor',
    conference: 'Big 12',
    projectedPoints: 6.5,
    rushingYards: 1601,
    rushingTDs: 12,
    receivingYards: 114,
    receptions: 15,
    receivingTDs: 0,
  },
  {
    id: 'rb32',
    name: 'Dameon Pierce',
    position: 'RB',
    team: 'Florida',
    conference: 'SEC',
    projectedPoints: 6.2,
    rushingYards: 574,
    rushingTDs: 13,
    receivingYards: 216,
    receptions: 19,
    receivingTDs: 3,
  },
  {
    id: 'rb33',
    name: 'Tyler Goodson',
    position: 'RB',
    team: 'Iowa',
    conference: 'Big Ten',
    projectedPoints: 5.9,
    rushingYards: 1151,
    rushingTDs: 6,
    receivingYards: 247,
    receptions: 28,
    receivingTDs: 1,
  },
  {
    id: 'rb34',
    name: 'D\'Eriq King',
    position: 'RB',
    team: 'Miami',
    conference: 'ACC',
    projectedPoints: 5.6,
    rushingYards: 538,
    rushingTDs: 4,
    receivingYards: 89,
    receptions: 12,
    receivingTDs: 1,
  },
  {
    id: 'rb35',
    name: 'Sincere McCormick',
    position: 'RB',
    team: 'UTSA',
    conference: 'C-USA',
    projectedPoints: 5.3,
    rushingYards: 1467,
    rushingTDs: 15,
    receivingYards: 225,
    receptions: 23,
    receivingTDs: 2,
  },
  {
    id: 'rb36',
    name: 'Jonathan Taylor',
    position: 'RB',
    team: 'Wisconsin',
    conference: 'Big Ten',
    projectedPoints: 5.0,
    rushingYards: 2003,
    rushingTDs: 21,
    receivingYards: 252,
    receptions: 26,
    receivingTDs: 5,
  },

  // Wide Receivers - Top Tier
  {
    id: 'wr1',
    name: 'Marvin Harrison Jr.',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 18.3,
    receivingYards: 1211,
    receptions: 67,
    receivingTDs: 14,
  },
  {
    id: 'wr2',
    name: 'Rome Odunze',
    position: 'WR',
    team: 'Washington',
    conference: 'Pac-12',
    projectedPoints: 17.8,
    receivingYards: 1640,
    receptions: 92,
    receivingTDs: 13,
  },
  {
    id: 'wr3',
    name: 'Malik Nabers',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 17.2,
    receivingYards: 1569,
    receptions: 89,
    receivingTDs: 14,
    returnYards: 234,
  },
  {
    id: 'wr4',
    name: 'Ladd McConkey',
    position: 'WR',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 16.5,
    receivingYards: 1187,
    receptions: 58,
    receivingTDs: 8,
    returnYards: 312,
  },
  {
    id: 'wr5',
    name: 'Keon Coleman',
    position: 'WR',
    team: 'Florida State',
    conference: 'ACC',
    projectedPoints: 16.1,
    receivingYards: 658,
    receptions: 50,
    receivingTDs: 11,
  },
  {
    id: 'wr6',
    name: 'Brian Thomas Jr.',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 15.8,
    receivingYards: 1177,
    receptions: 68,
    receivingTDs: 17,
  },
  {
    id: 'wr7',
    name: 'Xavier Worthy',
    position: 'WR',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 15.4,
    receivingYards: 1014,
    receptions: 75,
    receivingTDs: 5,
    returnYards: 156,
  },
  {
    id: 'wr8',
    name: 'Adonai Mitchell',
    position: 'WR',
    team: 'Texas',
    conference: 'Big 12',
    projectedPoints: 15.0,
    receivingYards: 845,
    receptions: 55,
    receivingTDs: 11,
  },
  {
    id: 'wr9',
    name: 'Troy Franklin',
    position: 'WR',
    team: 'Oregon',
    conference: 'Pac-12',
    projectedPoints: 14.7,
    receivingYards: 1383,
    receptions: 81,
    receivingTDs: 14,
  },
  {
    id: 'wr10',
    name: 'Emeka Egbuka',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 14.3,
    receivingYards: 1151,
    receptions: 69,
    receivingTDs: 10,
  },
  // Wide Receivers - Mid Tier
  {
    id: 'wr11',
    name: 'Jordan Addison',
    position: 'WR',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 14.0,
    receivingYards: 1593,
    receptions: 100,
    receivingTDs: 8,
  },
  {
    id: 'wr12',
    name: 'Jaylen Reed',
    position: 'WR',
    team: 'Michigan State',
    conference: 'Big Ten',
    projectedPoints: 13.7,
    receivingYards: 1026,
    receptions: 64,
    receivingTDs: 10,
  },
  {
    id: 'wr13',
    name: 'Jaxon Smith-Njigba',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 13.4,
    receivingYards: 347,
    receptions: 28,
    receivingTDs: 5,
  },
  {
    id: 'wr14',
    name: 'Quentin Johnston',
    position: 'WR',
    team: 'TCU',
    conference: 'Big 12',
    projectedPoints: 13.1,
    receivingYards: 1055,
    receptions: 60,
    receivingTDs: 6,
  },
  {
    id: 'wr15',
    name: 'Cedric Tillman',
    position: 'WR',
    team: 'Tennessee',
    conference: 'SEC',
    projectedPoints: 12.8,
    receivingYards: 1081,
    receptions: 64,
    receivingTDs: 12,
  },
  {
    id: 'wr16',
    name: 'Tre Tucker',
    position: 'WR',
    team: 'Cincinnati',
    conference: 'AAC',
    projectedPoints: 12.5,
    receivingYards: 761,
    receptions: 54,
    receivingTDs: 6,
    returnYards: 578,
  },
  {
    id: 'wr17',
    name: 'Dontay Demus Jr.',
    position: 'WR',
    team: 'Maryland',
    conference: 'Big Ten',
    projectedPoints: 12.2,
    receivingYards: 526,
    receptions: 27,
    receivingTDs: 3,
  },
  {
    id: 'wr18',
    name: 'Terrace Marshall Jr.',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 11.9,
    receivingYards: 671,
    receptions: 48,
    receivingTDs: 10,
  },
  {
    id: 'wr19',
    name: 'Chris Olave',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 11.6,
    receivingYards: 936,
    receptions: 65,
    receivingTDs: 13,
  },
  {
    id: 'wr20',
    name: 'DeVonta Smith',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 11.3,
    receivingYards: 1856,
    receptions: 117,
    receivingTDs: 23,
    returnYards: 89,
  },
  {
    id: 'wr21',
    name: 'Jerry Jeudy',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 11.0,
    receivingYards: 1163,
    receptions: 77,
    receivingTDs: 10,
  },
  {
    id: 'wr22',
    name: 'CeeDee Lamb',
    position: 'WR',
    team: 'Oklahoma',
    conference: 'Big 12',
    projectedPoints: 10.7,
    receivingYards: 1327,
    receptions: 62,
    receivingTDs: 14,
    returnYards: 235,
  },
  {
    id: 'wr23',
    name: 'Henry Ruggs III',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 10.4,
    receivingYards: 746,
    receptions: 40,
    receivingTDs: 7,
    returnYards: 123,
  },
  {
    id: 'wr24',
    name: 'Jaylen Waddle',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 10.1,
    receivingYards: 557,
    receptions: 45,
    receivingTDs: 4,
    returnYards: 194,
  },
  // More Wide Receivers
  {
    id: 'wr25',
    name: 'Ja\'Marr Chase',
    position: 'WR',
    team: 'LSU',
    conference: 'SEC',
    projectedPoints: 9.8,
    receivingYards: 1780,
    receptions: 84,
    receivingTDs: 20,
    returnYards: 156,
  },
  {
    id: 'wr26',
    name: 'Drake London',
    position: 'WR',
    team: 'USC',
    conference: 'Pac-12',
    projectedPoints: 9.5,
    receivingYards: 1084,
    receptions: 88,
    receivingTDs: 7,
  },
  {
    id: 'wr27',
    name: 'Garrett Wilson',
    position: 'WR',
    team: 'Ohio State',
    conference: 'Big Ten',
    projectedPoints: 9.2,
    receivingYards: 723,
    receptions: 43,
    receivingTDs: 12,
  },
  {
    id: 'wr28',
    name: 'Treylon Burks',
    position: 'WR',
    team: 'Arkansas',
    conference: 'SEC',
    projectedPoints: 8.9,
    receivingYards: 1104,
    receptions: 66,
    receivingTDs: 11,
  },
  {
    id: 'wr29',
    name: 'Skyy Moore',
    position: 'WR',
    team: 'Western Michigan',
    conference: 'MAC',
    projectedPoints: 8.6,
    receivingYards: 1292,
    receptions: 95,
    receivingTDs: 10,
  },
  {
    id: 'wr30',
    name: 'George Pickens',
    position: 'WR',
    team: 'Georgia',
    conference: 'SEC',
    projectedPoints: 8.3,
    receivingYards: 513,
    receptions: 36,
    receivingTDs: 5,
  },
  {
    id: 'wr31',
    name: 'Christian Watson',
    position: 'WR',
    team: 'North Dakota State',
    conference: 'FCS',
    projectedPoints: 8.0,
    receivingYards: 801,
    receptions: 43,
    receivingTDs: 7,
  },
  {
    id: 'wr32',
    name: 'Wan\'Dale Robinson',
    position: 'WR',
    team: 'Kentucky',
    conference: 'SEC',
    projectedPoints: 7.7,
    receivingYards: 1334,
    receptions: 104,
    receivingTDs: 7,
    rushingYards: 190,
    rushingTDs: 3,
  },
  {
    id: 'wr33',
    name: 'Jahan Dotson',
    position: 'WR',
    team: 'Penn State',
    conference: 'Big Ten',
    projectedPoints: 7.4,
    receivingYards: 1182,
    receptions: 91,
    receivingTDs: 12,
  },
  {
    id: 'wr34',
    name: 'Calvin Austin III',
    position: 'WR',
    team: 'Memphis',
    conference: 'AAC',
    projectedPoints: 7.1,
    receivingYards: 1149,
    receptions: 74,
    receivingTDs: 11,
    returnYards: 345,
  },
  {
    id: 'wr35',
    name: 'Tay McBride',
    position: 'WR',
    team: 'Colorado State',
    conference: 'Mountain West',
    projectedPoints: 6.8,
    receivingYards: 1121,
    receptions: 90,
    receivingTDs: 1,
  },
  {
    id: 'wr36',
    name: 'David Bell',
    position: 'WR',
    team: 'Purdue',
    conference: 'Big Ten',
    projectedPoints: 6.5,
    receivingYards: 1286,
    receptions: 93,
    receivingTDs: 6,
  },
  {
    id: 'wr37',
    name: 'Romeo Doubs',
    position: 'WR',
    team: 'Nevada',
    conference: 'Mountain West',
    projectedPoints: 6.2,
    receivingYards: 1002,
    receptions: 64,
    receivingTDs: 8,
  },
  {
    id: 'wr38',
    name: 'John Metchie III',
    position: 'WR',
    team: 'Alabama',
    conference: 'SEC',
    projectedPoints: 5.9,
    receivingYards: 1142,
    receptions: 96,
    receivingTDs: 8,
  },
  {
    id: 'wr39',
    name: 'Khalil Shakir',
    position: 'WR',
    team: 'Boise State',
    conference: 'Mountain West',
    projectedPoints: 5.6,
    receivingYards: 1117,
    receptions: 77,
    receivingTDs: 7,
  },
  {
    id: 'wr40',
    name: 'Alec Pierce',
    position: 'WR',
    team: 'Cincinnati',
    conference: 'AAC',
    projectedPoints: 5.3,
    receivingYards: 884,
    receptions: 52,
    receivingTDs: 8,
  },
  {
    id: 'wr41',
    name: 'Tyler Boyd',
    position: 'WR',
    team: 'Pittsburgh',
    conference: 'ACC',
    projectedPoints: 5.0,
    receivingYards: 1154,
    receptions: 85,
    receivingTDs: 8,
  },
  {
    id: 'wr42',
    name: 'Tyquan Thornton',
    position: 'WR',
    team: 'Baylor',
    conference: 'Big 12',
    projectedPoints: 4.7,
    receivingYards: 948,
    receptions: 62,
    receivingTDs: 10,
  },
  {
    id: 'wr43',
    name: 'Velus Jones Jr.',
    position: 'WR',
    team: 'Tennessee',
    conference: 'SEC',
    projectedPoints: 4.4,
    receivingYards: 807,
    receptions: 62,
    receivingTDs: 6,
    returnYards: 592,
  },
  {
    id: 'wr44',
    name: 'Justyn Ross',
    position: 'WR',
    team: 'Clemson',
    conference: 'ACC',
    projectedPoints: 4.1,
    receivingYards: 514,
    receptions: 46,
    receivingTDs: 3,
  },
  {
    id: 'wr45',
    name: 'Isaiah McKenzie',
    position: 'WR',
    team: 'Colorado',
    conference: 'Pac-12',
    projectedPoints: 3.8,
    receivingYards: 423,
    receptions: 34,
    receivingTDs: 2,
    returnYards: 187,
  },
  {
    id: 'wr46',
    name: 'Olave Johnson',
    position: 'WR',
    team: 'Tulsa',
    conference: 'AAC',
    projectedPoints: 3.5,
    receivingYards: 895,
    receptions: 68,
    receivingTDs: 4,
  },
  {
    id: 'wr47',
    name: 'Samson Nacua',
    position: 'WR',
    team: 'Utah',
    conference: 'Pac-12',
    projectedPoints: 3.2,
    receivingYards: 725,
    receptions: 52,
    receivingTDs: 6,
  },
  {
    id: 'wr48',
    name: 'Greg Dulcich',
    position: 'WR',
    team: 'UCLA',
    conference: 'Pac-12',
    projectedPoints: 2.9,
    receivingYards: 725,
    receptions: 42,
    receivingTDs: 5,
  },
];

// Conference lists for filtering
export const CONFERENCES = [
  'All Conferences',
  'SEC',
  'Big Ten',
  'Big 12',
  'ACC',
  'Pac-12',
  'AAC',
  'Independent',
  'Mountain West',
  'Sun Belt',
  'MAC',
  'C-USA',
  'FCS'
];

// Team lists for filtering
export const TEAMS = [
  'All Teams',
  // SEC
  'Alabama', 'Auburn', 'Florida', 'Georgia', 'LSU', 'Tennessee', 'Texas A&M', 'South Carolina', 'Kentucky', 'Arkansas',
  // Big Ten
  'Michigan', 'Ohio State', 'Michigan State', 'Illinois', 'Maryland', 'Penn State', 'Iowa', 'Wisconsin', 'Purdue',
  // Big 12
  'Texas', 'Oklahoma', 'TCU', 'Kansas State', 'UCF', 'Oklahoma State', 'Iowa State', 'Baylor', 'West Virginia',
  // ACC
  'Florida State', 'Miami', 'UNC', 'Pittsburgh', 'Syracuse', 'Georgia Tech', 'Louisville', 'Boston College', 'Clemson',
  // Pac-12
  'USC', 'Oregon', 'Washington', 'UCLA', 'Colorado', 'Utah', 'Oregon State', 'Stanford', 'Arizona State', 'Washington State',
  // AAC
  'Cincinnati', 'Tulane', 'Memphis', 'Tulsa',
  // Independent
  'BYU', 'Notre Dame',
  // Mountain West
  'Fresno State', 'Colorado State', 'Nevada', 'Boise State',
  // Sun Belt
  'Coastal Carolina',
  // MAC
  'Western Michigan',
  // C-USA
  'UTSA',
  // FCS
  'North Dakota State'
];