import { Player } from './types';

export const SAMPLE_PLAYERS: Player[] = [
  // Quarterbacks
  {
    id: 'qb1',
    name: 'Caleb Williams',
    position: 'QB',
    team: 'USC',
    projectedPoints: 22.5,
  },
  {
    id: 'qb2',
    name: 'Bo Nix',
    position: 'QB',
    team: 'Oregon',
    projectedPoints: 21.2,
  },
  {
    id: 'qb3',
    name: 'J.J. McCarthy',
    position: 'QB',
    team: 'Michigan',
    projectedPoints: 20.8,
  },
  {
    id: 'qb4',
    name: 'Quinn Ewers',
    position: 'QB',
    team: 'Texas',
    projectedPoints: 19.5,
  },
  {
    id: 'qb5',
    name: 'Carson Beck',
    position: 'QB',
    team: 'Georgia',
    projectedPoints: 18.9,
  },
  {
    id: 'qb6',
    name: 'Drake Maye',
    position: 'QB',
    team: 'UNC',
    projectedPoints: 18.2,
  },
  
  // Running Backs
  {
    id: 'rb1',
    name: 'Blake Corum',
    position: 'RB',
    team: 'Michigan',
    projectedPoints: 16.8,
  },
  {
    id: 'rb2',
    name: 'Bijan Robinson',
    position: 'RB',
    team: 'Texas',
    projectedPoints: 16.2,
  },
  {
    id: 'rb3',
    name: 'Travis Dye',
    position: 'RB',
    team: 'USC',
    projectedPoints: 15.5,
  },
  {
    id: 'rb4',
    name: 'Devon Achane',
    position: 'RB',
    team: 'Texas A&M',
    projectedPoints: 15.1,
  },
  {
    id: 'rb5',
    name: 'Zach Charbonnet',
    position: 'RB',
    team: 'UCLA',
    projectedPoints: 14.8,
  },
  {
    id: 'rb6',
    name: 'Sean Tucker',
    position: 'RB',
    team: 'Syracuse',
    projectedPoints: 14.3,
  },
  {
    id: 'rb7',
    name: 'Tank Bigsby',
    position: 'RB',
    team: 'Auburn',
    projectedPoints: 13.9,
  },
  {
    id: 'rb8',
    name: 'Israel Abanikanda',
    position: 'RB',
    team: 'Pittsburgh',
    projectedPoints: 13.5,
  },
  
  // Wide Receivers
  {
    id: 'wr1',
    name: 'Marvin Harrison Jr.',
    position: 'WR',
    team: 'Ohio State',
    projectedPoints: 18.3,
  },
  {
    id: 'wr2',
    name: 'Rome Odunze',
    position: 'WR',
    team: 'Washington',
    projectedPoints: 17.8,
  },
  {
    id: 'wr3',
    name: 'Malik Nabers',
    position: 'WR',
    team: 'LSU',
    projectedPoints: 17.2,
  },
  {
    id: 'wr4',
    name: 'Ladd McConkey',
    position: 'WR',
    team: 'Georgia',
    projectedPoints: 16.5,
  },
  {
    id: 'wr5',
    name: 'Keon Coleman',
    position: 'WR',
    team: 'Florida State',
    projectedPoints: 16.1,
  },
  {
    id: 'wr6',
    name: 'Brian Thomas Jr.',
    position: 'WR',
    team: 'LSU',
    projectedPoints: 15.8,
  },
  {
    id: 'wr7',
    name: 'Xavier Worthy',
    position: 'WR',
    team: 'Texas',
    projectedPoints: 15.4,
  },
  {
    id: 'wr8',
    name: 'Adonai Mitchell',
    position: 'WR',
    team: 'Texas',
    projectedPoints: 15.0,
  },
  {
    id: 'wr9',
    name: 'Troy Franklin',
    position: 'WR',
    team: 'Oregon',
    projectedPoints: 14.7,
  },
  {
    id: 'wr10',
    name: 'Emeka Egbuka',
    position: 'WR',
    team: 'Ohio State',
    projectedPoints: 14.3,
  },
];